[context.master.environment]
  VUE_APP_API_ENDPOINT=https://api.whynot.earth

[[redirects]]
  from = "/.well-known/assetlinks.json"
  to = "/assetlinks.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
